version: 2.1


jobs:

####################################################################
# Infrastructure creation job
####################################################################
  # create_infrastructure:
  #   docker:
  #     - image: amazon/aws-cli
    
  #   steps:
  #     - checkout
  #     - run:
  #         name: Create Cloudformation Stack
  #         command: |
  #           aws cloudformation deploy \
  #             --template-file infra-launcher.yml \
  #             --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #             --region us-east-1
####################################################################
#Infrastructure creation job ending
####################################################################

#####################################################################
#Smoke Test Job
#####################################################################

  smoke_test:
    docker:
      - image: python:3.7-alpine3.11
    
    steps:
      - checkout
      - run:
          name: Check connectivity of https://blog.udacity.com/ site
          command: |
            URL="https://blog.udacity.com/"

            if curl -s --head ${URL} 
            then
              return 0
            else
              return 1
            fi

workflows:
  # create-infrastructure-workflow:
  #   jobs:
  #     - create_infrastructure

  my-workflow:
    jobs:
      - smoke_test
